version: "3.8"

services:

  backend:
    image: backend-image
    ports:
      - "8079:8079"
    volumes:
      - ./src/backend:/app
    networks:
      - gisnet

  db:
    container_name: db
    image: postgis/postgis
    restart: "always"
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
    networks:
      gisnet:
        aliases:
          - postgis15.docker
  pgadmin4:
    image: dpage/pgadmin4
    restart: "always"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin_password
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 25
    ports:
      - "5480:80"
    networks:
      gisnet:
        aliases:
          - pgadmin4.docker
    volumes:
      - data:/data-postgis15-data
volumes:
  data:
    name: data-postgis15-data
  postgis_data:


networks:
  gisnet:
    name: gisnet
    external: true
